"use client";
import "../styles/fonts.css";
import "../styles/globals.css";
import { theme } from "@/theme/theme";
import { ChakraProvider } from "@chakra-ui/react";

// import type { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "valid8web",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ fontFamily: "Nunito,sans-serif" }}>
        <ChakraProvider theme={theme}>{children}</ChakraProvider>
      </body>
    </html>
  );
}
