"use client";
// import "./globals.css";
// import type { Metadata } from "next";
import { ChakraProvider} from "@chakra-ui/react";

import { theme } from "@/theme/theme";

// export const metadata: Metadata = {
//   title: "valid8web",
//   description: "Generated by create next app",
// };



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider theme={theme}>{children}</ChakraProvider>
      </body>
    </html>
  );
}
